/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DaySlotRecipe, RecipeCardData } from "./shared-types";
export { DaySlotRecipe, RecipeCardData } from "./shared-types";
export namespace Components {
    /**
     * A single meal-plan day. Displays the assigned recipe if present,
     * otherwise shows the "empty" slot content.
     */
    interface DaySlot {
        "day": string;
        /**
          * @default null
         */
        "recipe": DaySlotRecipe | null;
    }
    /**
     * Displays a recipe summary (image, title, category/area tags) with a
     * favorite toggle. Emits events instead of mutating state itself so the
     * host app (SvelteKit) owns all data.
     */
    interface RecipeCard {
        /**
          * Whether this recipe is currently favorited.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Recipe summary data. Passed as a JS object property from Svelte.
         */
        "recipe": RecipeCardData;
    }
    /**
     * Debounced search input. Emits searchSubmit both on debounce and on
     * explicit Enter/submit so the host can choose either live search or
     * submit only behavior.
     */
    interface SearchBar {
        /**
          * Debounce delay in ms before auto-emitting while typing.
          * @default 400
         */
        "debounce": number;
        /**
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface DaySlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDaySlotElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface SearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchBarElement;
}
declare global {
    interface HTMLDaySlotElementEventMap {
        "remove": { day: string };
        "slotClick": { day: string };
    }
    /**
     * A single meal-plan day. Displays the assigned recipe if present,
     * otherwise shows the "empty" slot content.
     */
    interface HTMLDaySlotElement extends Components.DaySlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDaySlotElementEventMap>(type: K, listener: (this: HTMLDaySlotElement, ev: DaySlotCustomEvent<HTMLDaySlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDaySlotElementEventMap>(type: K, listener: (this: HTMLDaySlotElement, ev: DaySlotCustomEvent<HTMLDaySlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDaySlotElement: {
        prototype: HTMLDaySlotElement;
        new (): HTMLDaySlotElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favoriteToggle": { id: string };
        "cardClick": { id: string };
    }
    /**
     * Displays a recipe summary (image, title, category/area tags) with a
     * favorite toggle. Emits events instead of mutating state itself so the
     * host app (SvelteKit) owns all data.
     */
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLSearchBarElementEventMap {
        "searchSubmit": string;
    }
    /**
     * Debounced search input. Emits searchSubmit both on debounce and on
     * explicit Enter/submit so the host can choose either live search or
     * submit only behavior.
     */
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "day-slot": HTMLDaySlotElement;
        "recipe-card": HTMLRecipeCardElement;
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * A single meal-plan day. Displays the assigned recipe if present,
     * otherwise shows the "empty" slot content.
     */
    interface DaySlot {
        "day": string;
        /**
          * Fires when the remove button is clicked.
         */
        "onRemove"?: (event: DaySlotCustomEvent<{ day: string }>) => void;
        /**
          * Fires when the slot itself (assigned or empty) is clicked.
         */
        "onSlotClick"?: (event: DaySlotCustomEvent<{ day: string }>) => void;
        /**
          * @default null
         */
        "recipe"?: DaySlotRecipe | null;
    }
    /**
     * Displays a recipe summary (image, title, category/area tags) with a
     * favorite toggle. Emits events instead of mutating state itself so the
     * host app (SvelteKit) owns all data.
     */
    interface RecipeCard {
        /**
          * Whether this recipe is currently favorited.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Fires when the card body is clicked (for navigation).
         */
        "onCardClick"?: (event: RecipeCardCustomEvent<{ id: string }>) => void;
        /**
          * Fires when the favorite icon is clicked.
         */
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<{ id: string }>) => void;
        /**
          * Recipe summary data. Passed as a JS object property from Svelte.
         */
        "recipe": RecipeCardData;
    }
    /**
     * Debounced search input. Emits searchSubmit both on debounce and on
     * explicit Enter/submit so the host can choose either live search or
     * submit only behavior.
     */
    interface SearchBar {
        /**
          * Debounce delay in ms before auto-emitting while typing.
          * @default 400
         */
        "debounce"?: number;
        /**
          * Fires with the current query string, on debounce or Enter/submit.
         */
        "onSearchSubmit"?: (event: SearchBarCustomEvent<string>) => void;
        /**
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface DaySlotAttributes {
        "day": string;
    }
    interface RecipeCardAttributes {
        "isFavorite": boolean;
    }
    interface SearchBarAttributes {
        "placeholder": string;
        "value": string;
        "debounce": number;
    }

    interface IntrinsicElements {
        "day-slot": Omit<DaySlot, keyof DaySlotAttributes> & { [K in keyof DaySlot & keyof DaySlotAttributes]?: DaySlot[K] } & { [K in keyof DaySlot & keyof DaySlotAttributes as `attr:${K}`]?: DaySlotAttributes[K] } & { [K in keyof DaySlot & keyof DaySlotAttributes as `prop:${K}`]?: DaySlot[K] } & OneOf<"day", DaySlot["day"], DaySlotAttributes["day"]>;
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "search-bar": Omit<SearchBar, keyof SearchBarAttributes> & { [K in keyof SearchBar & keyof SearchBarAttributes]?: SearchBar[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `attr:${K}`]?: SearchBarAttributes[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `prop:${K}`]?: SearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A single meal-plan day. Displays the assigned recipe if present,
             * otherwise shows the "empty" slot content.
             */
            "day-slot": LocalJSX.IntrinsicElements["day-slot"] & JSXBase.HTMLAttributes<HTMLDaySlotElement>;
            /**
             * Displays a recipe summary (image, title, category/area tags) with a
             * favorite toggle. Emits events instead of mutating state itself so the
             * host app (SvelteKit) owns all data.
             */
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            /**
             * Debounced search input. Emits searchSubmit both on debounce and on
             * explicit Enter/submit so the host can choose either live search or
             * submit only behavior.
             */
            "search-bar": LocalJSX.IntrinsicElements["search-bar"] & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
